# This file should contain all the recordion needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (ored alongside the db with db:setup).
#
# Examples:
#
#   cities = Citye([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayore(name: 'Emanuel', city: cities.first)

# SGSNs
Sgsn.find_or_create_by_name('3SGSNBPL1H')
Sgsn.find_or_create_by_name('3SGSNBPL2H')
Sgsn.find_or_create_by_name('3SGSNBPL3H')
Sgsn.find_or_create_by_name('3SGSNCMI1H')
Sgsn.find_or_create_by_name('3SGSNCWD2H')
Sgsn.find_or_create_by_name('3SGSNPLK1H')
Sgsn.find_or_create_by_name('3SGSNSNI1H')
Sgsn.find_or_create_by_name('3SGSNSUK1H')
Sgsn.find_or_create_by_name('3SGSNSUK2H')
Sgsn.find_or_create_by_name('3SGSNTWA2H')
Sgsn.find_or_create_by_name('3SGSNTWA3H')

puts "Sgsn has #{Sgsn.count} records in the table."

# Rncs
Rnc.find_or_create_by_name('3FGWCWD1A')
Rnc.find_or_create_by_name('3RNCBPL1H')
Rnc.find_or_create_by_name('3RNCBPL2H')
Rnc.find_or_create_by_name('3RNCBPL3H')
Rnc.find_or_create_by_name('3RNCCWD1H')
Rnc.find_or_create_by_name('3RNCCWD2H')
Rnc.find_or_create_by_name('3RNCCWD3H')
Rnc.find_or_create_by_name('3RNCTWA1H')
Rnc.find_or_create_by_name('3RNCTWA2H')
Rnc.find_or_create_by_name('3RNCTWA3H')
Rnc.find_or_create_by_name('3RNCCBI10N')
Rnc.find_or_create_by_name('3RNCCBI1N')
Rnc.find_or_create_by_name('3RNCCBI2N')
Rnc.find_or_create_by_name('3RNCCBI4N')
Rnc.find_or_create_by_name('3RNCCBI5N')
Rnc.find_or_create_by_name('3RNCCBI6N')
Rnc.find_or_create_by_name('3RNCCBI7N')
Rnc.find_or_create_by_name('3RNCCBI8N')
Rnc.find_or_create_by_name('3RNCCBI9N')
Rnc.find_or_create_by_name('3RNCNMA1Z')
Rnc.find_or_create_by_name('3RNCNMA2Z')
Rnc.find_or_create_by_name('3RNCNMA3Z')
Rnc.find_or_create_by_name('3RNCNMA4Z')
Rnc.find_or_create_by_name('3RNCNMA5Z')
Rnc.find_or_create_by_name('3RNCNMA6Z')
Rnc.find_or_create_by_name('3RNCNMA7Z')
Rnc.find_or_create_by_name('3FGWSUK1A')
Rnc.find_or_create_by_name('T3RNCTTC2N')
Rnc.find_or_create_by_name('3RNCCMI1H')
Rnc.find_or_create_by_name('3RNCCMI2H')
Rnc.find_or_create_by_name('3RNCCMI3H')
Rnc.find_or_create_by_name('3RNCCMI4H')
Rnc.find_or_create_by_name('3RNCAYA1Z')
Rnc.find_or_create_by_name('3RNCAYA2Z')
Rnc.find_or_create_by_name('3RNCAYA3Z')
Rnc.find_or_create_by_name('3RNCAYA4Z')
Rnc.find_or_create_by_name('3RNCAYA5Z')
Rnc.find_or_create_by_name('3RNCPLK1H')
Rnc.find_or_create_by_name('3RNCPLK2H')
Rnc.find_or_create_by_name('3RNCPLK3H')
Rnc.find_or_create_by_name('3RNCPLK4H')
Rnc.find_or_create_by_name('3RNCSNI1H')
Rnc.find_or_create_by_name('3RNCSNI2H')
Rnc.find_or_create_by_name('3RNCSNI3H')
Rnc.find_or_create_by_name('3RNCSNI4H')
Rnc.find_or_create_by_name('RNCSNI1H')
Rnc.find_or_create_by_name('3RNCSUK1H')
Rnc.find_or_create_by_name('3RNCSUK2H')
Rnc.find_or_create_by_name('3RNCSUK3H')
Rnc.find_or_create_by_name('3RNCKKN1Z')
Rnc.find_or_create_by_name('3RNCKKN2Z')
Rnc.find_or_create_by_name('3RNCKKN3Z')
Rnc.find_or_create_by_name('3RNCKKN4Z')
Rnc.find_or_create_by_name('3RNCKKN5Z')
Rnc.find_or_create_by_name('3RNCKKN6Z')
Rnc.find_or_create_by_name('3RNCKKN7Z')
Rnc.find_or_create_by_name('3RNCPTY10N')
Rnc.find_or_create_by_name('3RNCPTY1N')
Rnc.find_or_create_by_name('3RNCPTY2N')
Rnc.find_or_create_by_name('3RNCPTY3N')
Rnc.find_or_create_by_name('3RNCPTY4N')
Rnc.find_or_create_by_name('3RNCPTY5N')
Rnc.find_or_create_by_name('3RNCPTY6N')
Rnc.find_or_create_by_name('3RNCPTY7N')
Rnc.find_or_create_by_name('3RNCPTY8N')
Rnc.find_or_create_by_name('3RNCPTY9N')
Rnc.find_or_create_by_name('3RNCNPT1Z')
Rnc.find_or_create_by_name('3RNCNPT2Z')
Rnc.find_or_create_by_name('3RNCNPT3Z')
Rnc.find_or_create_by_name('3RNCNPT4Z')
Rnc.find_or_create_by_name('3RNCNPT5Z')
Rnc.find_or_create_by_name('3RNCHYI1H')
Rnc.find_or_create_by_name('3RNCHYI2H')
Rnc.find_or_create_by_name('3RNCHYI3H')
Rnc.find_or_create_by_name('3RNCHYI4H')
Rnc.find_or_create_by_name('3RNCCBI3N')

puts "Rnc has #{Rnc.count} records in the table."

def RncSgsnMapping(params)
  sgsn = Sgsn.find_by_name(params[:sgsn_name])
  rnc = Rnc.find_by_name(params[:rnc_name])
  rnc.sgsn = sgsn
  rnc.save
end

# Update mapping between RCNs and SGSNs
RncSgsnMapping(rnc_name: '3FGWCWD1A', sgsn_name: '3SGSNBPL1H')
RncSgsnMapping(rnc_name: '3RNCBPL1H', sgsn_name: '3SGSNBPL1H')
RncSgsnMapping(rnc_name: '3RNCBPL2H', sgsn_name: '3SGSNBPL1H')
RncSgsnMapping(rnc_name: '3RNCBPL3H', sgsn_name: '3SGSNBPL1H')
RncSgsnMapping(rnc_name: '3RNCCWD1H', sgsn_name: '3SGSNBPL1H')
RncSgsnMapping(rnc_name: '3RNCCWD2H', sgsn_name: '3SGSNBPL1H')
RncSgsnMapping(rnc_name: '3RNCCWD3H', sgsn_name: '3SGSNBPL1H')
RncSgsnMapping(rnc_name: '3RNCTWA1H', sgsn_name: '3SGSNBPL1H')
RncSgsnMapping(rnc_name: '3RNCTWA2H', sgsn_name: '3SGSNBPL1H')
RncSgsnMapping(rnc_name: '3RNCTWA3H', sgsn_name: '3SGSNBPL1H')
RncSgsnMapping(rnc_name: '3RNCCBI10N', sgsn_name: '3SGSNBPL2H')
RncSgsnMapping(rnc_name: '3RNCCBI1N', sgsn_name: '3SGSNBPL2H')
RncSgsnMapping(rnc_name: '3RNCCBI2N', sgsn_name: '3SGSNBPL2H')
RncSgsnMapping(rnc_name: '3RNCCBI4N', sgsn_name: '3SGSNBPL2H')
RncSgsnMapping(rnc_name: '3RNCCBI5N', sgsn_name: '3SGSNBPL2H')
RncSgsnMapping(rnc_name: '3RNCCBI6N', sgsn_name: '3SGSNBPL2H')
RncSgsnMapping(rnc_name: '3RNCCBI7N', sgsn_name: '3SGSNBPL2H')
RncSgsnMapping(rnc_name: '3RNCCBI8N', sgsn_name: '3SGSNBPL2H')
RncSgsnMapping(rnc_name: '3RNCCBI9N', sgsn_name: '3SGSNBPL2H')
RncSgsnMapping(rnc_name: '3RNCNMA1Z', sgsn_name: '3SGSNBPL2H')
RncSgsnMapping(rnc_name: '3RNCNMA2Z', sgsn_name: '3SGSNBPL2H')
RncSgsnMapping(rnc_name: '3RNCNMA3Z', sgsn_name: '3SGSNBPL2H')
RncSgsnMapping(rnc_name: '3RNCNMA4Z', sgsn_name: '3SGSNBPL2H')
RncSgsnMapping(rnc_name: '3RNCNMA5Z', sgsn_name: '3SGSNBPL2H')
RncSgsnMapping(rnc_name: '3RNCNMA6Z', sgsn_name: '3SGSNBPL2H')
RncSgsnMapping(rnc_name: '3RNCNMA7Z', sgsn_name: '3SGSNBPL2H')
RncSgsnMapping(rnc_name: '3FGWSUK1A', sgsn_name: '3SGSNBPL3H')
RncSgsnMapping(rnc_name: 'T3RNCTTC2N', sgsn_name: '3SGSNBPL3H')
RncSgsnMapping(rnc_name: '3RNCCMI1H', sgsn_name: '3SGSNCMI1H')
RncSgsnMapping(rnc_name: '3RNCCMI2H', sgsn_name: '3SGSNCMI1H')
RncSgsnMapping(rnc_name: '3RNCCMI3H', sgsn_name: '3SGSNCMI1H')
RncSgsnMapping(rnc_name: '3RNCCMI4H', sgsn_name: '3SGSNCMI1H')
RncSgsnMapping(rnc_name: '3RNCAYA1Z', sgsn_name: '3SGSNCWD2H')
RncSgsnMapping(rnc_name: '3RNCAYA2Z', sgsn_name: '3SGSNCWD2H')
RncSgsnMapping(rnc_name: '3RNCAYA3Z', sgsn_name: '3SGSNCWD2H')
RncSgsnMapping(rnc_name: '3RNCAYA4Z', sgsn_name: '3SGSNCWD2H')
RncSgsnMapping(rnc_name: '3RNCAYA5Z', sgsn_name: '3SGSNCWD2H')
RncSgsnMapping(rnc_name: '3RNCPLK1H', sgsn_name: '3SGSNPLK1H')
RncSgsnMapping(rnc_name: '3RNCPLK2H', sgsn_name: '3SGSNPLK1H')
RncSgsnMapping(rnc_name: '3RNCPLK3H', sgsn_name: '3SGSNPLK1H')
RncSgsnMapping(rnc_name: '3RNCPLK4H', sgsn_name: '3SGSNPLK1H')
RncSgsnMapping(rnc_name: '3RNCSNI1H', sgsn_name: '3SGSNSNI1H')
RncSgsnMapping(rnc_name: '3RNCSNI2H', sgsn_name: '3SGSNSNI1H')
RncSgsnMapping(rnc_name: '3RNCSNI3H', sgsn_name: '3SGSNSNI1H')
RncSgsnMapping(rnc_name: '3RNCSNI4H', sgsn_name: '3SGSNSNI1H')
RncSgsnMapping(rnc_name: 'RNCSNI1H', sgsn_name: '3SGSNSNI1H')
RncSgsnMapping(rnc_name: '3RNCSUK1H', sgsn_name: '3SGSNSUK1H')
RncSgsnMapping(rnc_name: '3RNCSUK2H', sgsn_name: '3SGSNSUK1H')
RncSgsnMapping(rnc_name: '3RNCSUK3H', sgsn_name: '3SGSNSUK1H')
RncSgsnMapping(rnc_name: '3RNCKKN1Z', sgsn_name: '3SGSNSUK2H')
RncSgsnMapping(rnc_name: '3RNCKKN2Z', sgsn_name: '3SGSNSUK2H')
RncSgsnMapping(rnc_name: '3RNCKKN3Z', sgsn_name: '3SGSNSUK2H')
RncSgsnMapping(rnc_name: '3RNCKKN4Z', sgsn_name: '3SGSNSUK2H')
RncSgsnMapping(rnc_name: '3RNCKKN5Z', sgsn_name: '3SGSNSUK2H')
RncSgsnMapping(rnc_name: '3RNCKKN6Z', sgsn_name: '3SGSNSUK2H')
RncSgsnMapping(rnc_name: '3RNCKKN7Z', sgsn_name: '3SGSNSUK2H')
RncSgsnMapping(rnc_name: '3RNCPTY10N', sgsn_name: '3SGSNSUK2H')
RncSgsnMapping(rnc_name: '3RNCPTY1N', sgsn_name: '3SGSNSUK2H')
RncSgsnMapping(rnc_name: '3RNCPTY2N', sgsn_name: '3SGSNSUK2H')
RncSgsnMapping(rnc_name: '3RNCPTY3N', sgsn_name: '3SGSNSUK2H')
RncSgsnMapping(rnc_name: '3RNCPTY4N', sgsn_name: '3SGSNSUK2H')
RncSgsnMapping(rnc_name: '3RNCPTY5N', sgsn_name: '3SGSNSUK2H')
RncSgsnMapping(rnc_name: '3RNCPTY6N', sgsn_name: '3SGSNSUK2H')
RncSgsnMapping(rnc_name: '3RNCPTY7N', sgsn_name: '3SGSNSUK2H')
RncSgsnMapping(rnc_name: '3RNCPTY8N', sgsn_name: '3SGSNSUK2H')
RncSgsnMapping(rnc_name: '3RNCPTY9N', sgsn_name: '3SGSNSUK2H')
RncSgsnMapping(rnc_name: '3RNCNPT1Z', sgsn_name: '3SGSNTWA2H')
RncSgsnMapping(rnc_name: '3RNCNPT2Z', sgsn_name: '3SGSNTWA2H')
RncSgsnMapping(rnc_name: '3RNCNPT3Z', sgsn_name: '3SGSNTWA2H')
RncSgsnMapping(rnc_name: '3RNCNPT4Z', sgsn_name: '3SGSNTWA2H')
RncSgsnMapping(rnc_name: '3RNCNPT5Z', sgsn_name: '3SGSNTWA2H')
RncSgsnMapping(rnc_name: '3RNCHYI1H', sgsn_name: '3SGSNTWA3H')
RncSgsnMapping(rnc_name: '3RNCHYI2H', sgsn_name: '3SGSNTWA3H')
RncSgsnMapping(rnc_name: '3RNCHYI3H', sgsn_name: '3SGSNTWA3H')
RncSgsnMapping(rnc_name: '3RNCHYI4H', sgsn_name: '3SGSNTWA3H')
RncSgsnMapping(rnc_name: '3RNCCBI3N', sgsn_name: '3SGSNBPL2H')